---
abstract: unknown
author:
  - 'Ricardo SIGNES <rjbs@cpan.org >'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: E-Mail-Acme
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: http://github.com/rjbs/E-Mail-Acme/issues
  repository: http://github.com/rjbs/E-Mail-Acme
version: 1555
